# Generated by Django 2.2 on 2019-06-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='serdes_num_fabric',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='serdes_num_front',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='serdes_speed_fabric',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='serdes_speed_front',
        ),
        migrations.AddField(
            model_name='mac',
            name='speed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mac',
            name='unit',
            field=models.CharField(default='G', max_length=20),
        ),
        migrations.AddField(
            model_name='serdesspeed',
            name='speed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serdesspeed',
            name='unit',
            field=models.CharField(default='G', max_length=20),
        ),
        migrations.AlterField(
            model_name='chip',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
