# Generated by Django 2.2 on 2019-06-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_model', '0002_auto_20190604_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulebuild',
            name='ports',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ModuleBuildPorts',
        ),
    ]
