# Generated by Django 2.2 on 2019-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_model', '0003_auto_20190604_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipmodelno',
            name='code_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
