# Generated by Django 2.2 on 2019-06-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_model', '0006_auto_20190604_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='fif_serdes',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='fif_serdes_num',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='nif_serdes',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='nif_serdes_num',
        ),
    ]
