# Generated by Django 2.2 on 2019-05-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='serdes_speed_fabric',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chip',
            name='serdes_speed_front',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulebuild',
            name='fqdn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='fqdn',
            field=models.URLField(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_build',
        ),
        migrations.AddField(
            model_name='module',
            name='module_build',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ModuleBuild'),
            preserve_default=False,
        ),
    ]
