# Generated by Django 2.2 on 2019-05-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190502_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='module',
        ),
    ]
