# Generated by Django 2.2 on 2019-05-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_device_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.DeviceType'),
        ),
    ]
