# Generated by Django 2.2 on 2019-05-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190514_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelno',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='modelno',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
